### ISSUE TITLE
Interested in making a new scoped version of keyv?

### ISSUE THREAD

**Issue by Jytesh** [microlinkhq/keyv-redis#1]
lukechilds appears to be busy with other stuff and stopped updating keyv ( last update was 7 months ago ), if you are interested we can make an org and publish a scoped version of keyv that we can update.

@Kikobeats I have already published keyv-sql, keyv-sqlite and keyv-mongo, under my user scope with some useful patches.

**Comment by Kikobeats** [comment]
I'm totally interested!

I created https://github.com/keyvhq and invited you; we can move all our stuff there and create a new roadmap for this project.

**Comment by Jytesh** [comment]
@Kikobeats Awesome! paging @caseyWebb as well

**Comment by Kikobeats** [comment]
I think @sindresorhus and @szmarczak could be interested too since it's used at [ghub.io/got](https://ghub.io/got) widely

**Comment by Kikobeats** [comment]
If anyone is interested on this, please feel free to ping me and I will add you as part of the organization 🙂
